# Generated by Django 5.0.1 on 2024-01-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
